name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.3.1
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: 3.7.8

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  dio: ^5.0.3
  flutter_local_notifications: ^13.0.0
  rxdart: ^0.27.5

  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  package_info_plus: ^3.0.3
  sensors_plus: ^2.0.2
  share_plus: ^6.3.1
  chopper: ^6.1.1
  better_player: ^0.0.83
  collection: ^1.17.0

dev_dependencies:
  lint: ^2.0.1
